[project]
name = "server"
version = "0.0.1"
description = "FastAPI Server Starter"
readme = "README.md"
requires-python = "==3.14.3"
dependencies = [
    "fastapi==0.129.2",
    "gunicorn==25.1.0",
    "pydantic==2.12.5",
    "uvicorn==0.41.0",
]
